import React, { useState, useEffect } from 'react';
import { User } from 'firebase/auth';
import { 
  initAuth, 
  googleSignIn, 
  logout, 
  getAccessToken 
} from '../lib/firebase';
import { UnifiedPosition, UnifiedOrder, LogMessage, Account } from '../types';
import { 
  Cloud, 
  CheckCircle, 
  ExternalLink, 
  Trash2, 
  LogOut, 
  UploadCloud, 
  FileSpreadsheet, 
  FileText, 
  RefreshCw, 
  Database,
  Lock,
  AlertCircle,
  HelpCircle,
  TrendingUp,
  History
} from 'lucide-react';

interface GoogleDriveManagerProps {
  positions: UnifiedPosition[];
  orders: UnifiedOrder[];
  logs: LogMessage[];
  accounts: Account[];
  onAddSystemLog?: (message: string, level: 'success' | 'info' | 'error') => void;
}

interface DriveFile {
  id: string;
  name: string;
  mimeType: string;
  size?: string;
  createdTime: string;
  webViewLink?: string;
}

export default function GoogleDriveManager({ 
  positions, 
  orders, 
  logs, 
  accounts,
  onAddSystemLog 
}: GoogleDriveManagerProps) {
  // Authentication states
  const [user, setUser] = useState<User | null>(null);
  const [token, setToken] = useState<string | null>(null);
  const [needsAuth, setNeedsAuth] = useState(true);
  const [isLoggingIn, setIsLoggingIn] = useState(false);

  // File explorer states
  const [files, setFiles] = useState<DriveFile[]>([]);
  const [isLoadingFiles, setIsLoadingFiles] = useState(false);
  const [explorerError, setExplorerError] = useState<string | null>(null);

  // Export action states
  const [isExporting, setIsExporting] = useState<Record<string, boolean>>({});
  const [exportMessage, setExportMessage] = useState<{ text: string; type: 'success' | 'error' } | null>(null);

  // Initialize Auth state listener
  useEffect(() => {
    const unsubscribe = initAuth(
      (firebaseUser, accessToken) => {
        setUser(firebaseUser);
        setToken(accessToken);
        setNeedsAuth(false);
        // Load files from Google Drive
        fetchDriveFiles(accessToken);
      },
      () => {
        setUser(null);
        setToken(null);
        setNeedsAuth(true);
      }
    );
    return () => unsubscribe();
  }, []);

  // Sign In flow
  const handleSignIn = async () => {
    setIsLoggingIn(true);
    setExportMessage(null);
    try {
      const result = await googleSignIn();
      if (result) {
        setUser(result.user);
        setToken(result.accessToken);
        setNeedsAuth(false);
        if (onAddSystemLog) {
          onAddSystemLog('Linked Google Drive account successfully via OAuth provider.', 'success');
        }
        fetchDriveFiles(result.accessToken);
      }
    } catch (err: any) {
      console.error('OAuth configuration failed:', err);
      setExplorerError('OAuth handshake failed or cancelled. Please verify credentials.');
    } finally {
      setIsLoggingIn(false);
    }
  };

  // Sign Out flow
  const handleSignOut = async () => {
    if (window.confirm('Are you sure you want to disconnect Google Drive? This will clear session credentials.')) {
      try {
        await logout();
        setUser(null);
        setToken(null);
        setNeedsAuth(true);
        setFiles([]);
        if (onAddSystemLog) {
          onAddSystemLog('Google Drive session credentials revoked.', 'info');
        }
      } catch (err) {
        console.error('Sign-out failed', err);
      }
    }
  };

  // Load files generated by MoneyTree from Google Drive
  const fetchDriveFiles = async (accessToken: string) => {
    if (!accessToken) return;
    setIsLoadingFiles(true);
    setExplorerError(null);
    try {
      // Fetch only non-trashed files containing 'MoneyTree_' inside user's drive
      const query = encodeURIComponent("name contains 'MoneyTree_' and trashed = false");
      const url = `https://www.googleapis.com/drive/v3/files?q=${query}&orderBy=createdTime desc&fields=files(id,name,mimeType,size,createdTime,webViewLink)&pageSize=25`;
      
      const response = await fetch(url, {
        headers: {
          'Authorization': `Bearer ${accessToken}`
        }
      });

      if (!response.ok) {
        if (response.status === 401) {
          // Token expired or invalid
          setNeedsAuth(true);
          return;
        }
        throw new Error(`Google API returned status: ${response.status}`);
      }

      const data = await response.json();
      setFiles(data.files || []);
    } catch (err: any) {
      console.error('Error listing Drive file collections:', err);
      setExplorerError(err.message || 'Unable to scan Google Drive records.');
    } finally {
      setIsLoadingFiles(false);
    }
  };

  const refreshFiles = () => {
    if (token) fetchDriveFiles(token);
  };

  // Delete file handler
  const handleDeleteFile = async (fileId: string, filename: string) => {
    if (!token) return;
    const confirmed = window.confirm(`Permanently delete "${filename}" from Google Drive? This action cannot be revoked.`);
    if (!confirmed) return;

    try {
      const response = await fetch(`https://www.googleapis.com/drive/v3/files/${fileId}`, {
        method: 'DELETE',
        headers: {
          'Authorization': `Bearer ${token}`
        }
      });

      if (!response.ok) {
        throw new Error(`Failed to delete file. Status: ${response.status}`);
      }

      // Update state
      setFiles(prev => prev.filter(f => f.id !== fileId));
      setExportMessage({ text: 'File permanently purged from Drive.', type: 'success' });
      if (onAddSystemLog) {
        onAddSystemLog(`Purged report file "${filename}" from Google Drive.`, 'info');
      }
    } catch (err: any) {
      console.error('Error deleting file:', err);
      alert(`Error deleting file: ${err.message}`);
    }
  };

  // Upload helpers (Two step: Metadata -> Upload content)
  const uploadToDrive = async (filename: string, content: string, mimeType: string) => {
    if (!token) throw new Error('Unauthenticated session');

    // Step 1: Create file listing metadata
    const metadataResponse = await fetch('https://www.googleapis.com/drive/v3/files', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${token}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        name: filename,
        mimeType: mimeType
      })
    });

    if (!metadataResponse.ok) {
      throw new Error(`Metadata creation failed. Status: ${metadataResponse.status}`);
    }

    const metadata = await metadataResponse.json();
    const fileId = metadata.id;

    // Step 2: Upload media body content to that file ID
    const mediaResponse = await fetch(`https://www.googleapis.com/upload/drive/v3/files/${fileId}?uploadType=media`, {
      method: 'PATCH',
      headers: {
        'Authorization': `Bearer ${token}`,
        'Content-Type': mimeType
      },
      body: content
    });

    if (!mediaResponse.ok) {
      throw new Error(`Media body upload failed. Status: ${mediaResponse.status}`);
    }

    // Refresh file explorer desk
    await fetchDriveFiles(token);
    return fileId;
  };

  // Export Active Positions CSV
  const handleExportPositions = async () => {
    if (!token) return;
    const confirmed = window.confirm('Generate and export active positions portfolio report to Google Drive?');
    if (!confirmed) return;

    setIsExporting(prev => ({ ...prev, positions: true }));
    setExportMessage(null);

    try {
      const timestamp = new Date().toISOString().replace(/T/, '_').replace(/:/g, '-').slice(0, 19);
      const filename = `MoneyTree_Positions_${timestamp}.csv`;

      // Build CSV content
      let csv = 'Account_ID,Account_Name,Venue,Symbol,Position_Quantity,Average_Price,Last_Price,Unrealized_PNL\n';
      positions.forEach(p => {
        const acc = accounts.find(a => a.id === p.accountId);
        const name = acc ? acc.name : 'Unknown';
        csv += `"${p.accountId}","${name}","${p.venue}","${p.symbol}",${p.quantity},${p.averagePrice},${p.currentPrice},${p.unrealizedPnl}\n`;
      });

      await uploadToDrive(filename, csv, 'text/csv');
      setExportMessage({ text: `Success! Exported: "${filename}" to Google Drive.`, type: 'success' });
      
      if (onAddSystemLog) {
        onAddSystemLog(`Exported ${positions.length} portfolio positions to Google Drive: "${filename}"`, 'success');
      }
    } catch (err: any) {
      console.error('Export failed:', err);
      setExportMessage({ text: `Export failed: ${err.message}`, type: 'error' });
    } finally {
      setIsExporting(prev => ({ ...prev, positions: false }));
    }
  };

  // Export Order Logs CSV
  const handleExportOrders = async () => {
    if (!token) return;
    const confirmed = window.confirm('Generate and export full unified order history registry to Google Drive?');
    if (!confirmed) return;

    setIsExporting(prev => ({ ...prev, orders: true }));
    setExportMessage(null);

    try {
      const timestamp = new Date().toISOString().replace(/T/, '_').replace(/:/g, '-').slice(0, 19);
      const filename = `MoneyTree_Orders_${timestamp}.csv`;

      // Build CSV content
      let csv = 'Order_ID,Account_ID,Account_Name,Venue,Symbol,Side,Type,Price,Quantity,Status,Timestamp\n';
      orders.forEach(o => {
        const acc = accounts.find(a => a.id === o.accountId);
        const name = acc ? acc.name : 'Unknown';
        csv += `"${o.id}","${o.accountId}","${name}","${o.venue}","${o.symbol}","${o.side}","${o.type}",${o.price},${o.quantity},"${o.status}","${o.timestamp}"\n`;
      });

      await uploadToDrive(filename, csv, 'text/csv');
      setExportMessage({ text: `Success! Exported: "${filename}" to Google Drive.`, type: 'success' });

      if (onAddSystemLog) {
        onAddSystemLog(`Exported ${orders.length} transaction orders to Google Drive: "${filename}"`, 'success');
      }
    } catch (err: any) {
      console.error('Export failed:', err);
      setExportMessage({ text: `Export failed: ${err.message}`, type: 'error' });
    } finally {
      setIsExporting(prev => ({ ...prev, orders: false }));
    }
  };

  // Export Audit logs
  const handleExportLogs = async () => {
    if (!token) return;
    const confirmed = window.confirm('Generate and export system diagnostic audit logs to Google Drive?');
    if (!confirmed) return;

    setIsExporting(prev => ({ ...prev, logs: true }));
    setExportMessage(null);

    try {
      const timestamp = new Date().toISOString().replace(/T/, '_').replace(/:/g, '-').slice(0, 19);
      const filename = `MoneyTree_Audit_Logs_${timestamp}.log`;

      // Build log content text
      let textContent = `=======================================================\n`;
      textContent += `MONEYTREE TRADING SYSTEM INTEGRITY AUDIT REPORT\n`;
      textContent += `Export Time: ${new Date().toLocaleString()}\n`;
      textContent += `Active Accounts: ${accounts.length}\n`;
      textContent += `Active Orders: ${orders.length}\n`;
      textContent += `Active Positions: ${positions.length}\n`;
      textContent += `=======================================================\n\n`;

      logs.forEach(log => {
        textContent += `[${new Date(log.timestamp).toLocaleString()}] [${log.level.toUpperCase()}] [${log.source.toUpperCase()}] ${log.message}\n`;
      });

      await uploadToDrive(filename, textContent, 'text/plain');
      setExportMessage({ text: `Success! Exported: "${filename}" to Google Drive.`, type: 'success' });

      if (onAddSystemLog) {
        onAddSystemLog(`Exported ${logs.length} system log messages to Google Drive: "${filename}"`, 'success');
      }
    } catch (err: any) {
      console.error('Export failed:', err);
      setExportMessage({ text: `Export failed: ${err.message}`, type: 'error' });
    } finally {
      setIsExporting(prev => ({ ...prev, logs: false }));
    }
  };

  // Helper to format byte sizes
  const formatBytes = (bytesStr?: string | number) => {
    if (!bytesStr) return 'N/A';
    const bytes = typeof bytesStr === 'string' ? parseInt(bytesStr, 10) : bytesStr;
    if (isNaN(bytes)) return 'N/A';
    if (bytes === 0) return '0 B';
    const k = 1024;
    const sizes = ['B', 'KB', 'MB', 'GB'];
    const i = Math.floor(Math.log(bytes) / Math.log(k));
    return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i];
  };

  return (
    <div className="bg-[#111214] rounded-lg border border-[#2D2F31] flex flex-col h-full overflow-hidden select-none">
      {/* Header Panel */}
      <div className="flex items-center justify-between px-4 py-2.5 bg-[#161719] border-b border-[#2D2F31] shrink-0">
        <div className="flex items-center gap-2">
          <Cloud className="w-4 h-4 text-blue-500 animate-pulse" />
          <span className="text-xs font-bold tracking-wider text-white font-mono">GOOGLE DRIVE EXPORT PIPELINE</span>
        </div>
        
        {user && (
          <div className="flex items-center gap-3">
            <div className="flex items-center gap-2 text-right">
              <span className="hidden md:inline text-[10px] font-mono text-[#8E9299]">Linked Profile:</span>
              <span className="text-[11px] font-mono font-bold text-slate-100">{user.displayName || user.email}</span>
            </div>
            {user.photoURL && (
              <img 
                src={user.photoURL} 
                alt="Avatar" 
                className="w-5 h-5 rounded-full border border-blue-500/40" 
                referrerPolicy="no-referrer" 
              />
            )}
            <button
              onClick={handleSignOut}
              className="p-1 px-1.5 bg-[#1A1C1E] border border-[#2D2F31] hover:border-red-900/60 hover:text-red-400 rounded text-[#8E9299] transition-colors flex items-center gap-1 cursor-pointer text-[9px] font-mono"
              title="Sign Out Google session"
              id="btn_gdrive_logout"
            >
              <LogOut className="w-3 h-3" />
              <span>DISCONNECT</span>
            </button>
          </div>
        )}
      </div>

      {/* Main Container */}
      <div className="flex-1 overflow-y-auto p-4 flex flex-col gap-4">
        {needsAuth ? (
          /* Unauthenticated Landing Layout with Material Styled Sign In */
          <div className="flex-1 flex flex-col items-center justify-center py-10 max-w-md mx-auto text-center">
            <div className="w-12 h-12 rounded-full bg-blue-950/30 border border-blue-500/30 flex items-center justify-center mb-4">
              <Cloud className="w-6 h-6 text-blue-400" />
            </div>
            
            <h3 className="text-xs font-bold text-white uppercase tracking-wider mb-2 font-mono">Connect Secure Google Cloud Vault</h3>
            <p className="text-[11px] text-[#8E9299] font-mono leading-relaxed mb-6">
              Establish a direct, sandboxed encryption pipeline to Google Drive with permission from the app's users. Once authenticated, you can securely snapshot, catalog, and export active live trade positions, transactional order registries, and diagnostic environment logs securely as persistent sheets or text logs.
            </p>

            <button 
              onClick={handleSignIn}
              disabled={isLoggingIn}
              className="gsi-material-button w-full sm:w-auto relative inline-flex items-center justify-center p-0.5 mb-2 mr-2 overflow-hidden text-xs font-medium text-gray-900 rounded-lg group bg-gradient-to-br from-blue-600 to-indigo-500 group-hover:from-blue-600 group-hover:to-indigo-500 hover:text-white dark:text-white focus:ring-4 focus:outline-none focus:ring-blue-800 cursor-pointer disabled:opacity-50"
              id="btn_gdrive_signin"
            >
              <div className="flex items-center gap-2.5 bg-[#1A1C1E] border border-[#2D2F31] hover:bg-[#111214] transition-colors rounded-md p-2.5 text-slate-100 font-mono text-[11px] font-bold w-full">
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48" className="w-4 h-4 shrink-0">
                  <path fill="#EA4335" d="M24 9.5c3.54 0 6.71 1.22 9.21 3.6l6.85-6.85C35.9 2.38 30.47 0 24 0 14.62 0 6.51 5.38 2.56 13.22l7.98 6.19C12.43 13.72 17.74 9.5 24 9.5z"></path>
                  <path fill="#4285F4" d="M46.98 24.55c0-1.57-.15-3.09-.38-4.55H24v9.02h12.94c-.58 2.96-2.26 5.48-4.78 7.18l7.73 6c4.51-4.18 7.09-10.36 7.09-17.65z"></path>
                  <path fill="#FBBC05" d="M10.53 28.59c-.48-1.45-.76-2.99-.76-4.59s.27-3.14.76-4.59l-7.98-6.19C.92 16.46 0 20.12 0 24c0 3.88.92 7.54 2.56 10.78l7.97-6.19z"></path>
                  <path fill="#34A853" d="M24 48c6.48 0 11.93-2.13 15.89-5.81l-7.73-6c-2.15 1.45-4.92 2.3-8.16 2.3-6.26 0-11.57-4.22-13.47-9.91l-7.98 6.19C6.51 42.62 14.62 48 24 48z"></path>
                </svg>
                <span>{isLoggingIn ? 'AUTHENTICATING HANDSHAKE...' : 'LINK GOOGLE DRIVE'}</span>
              </div>
            </button>
            
            {explorerError && (
              <p className="mt-3 text-[10px] font-mono text-red-400 bg-red-950/20 p-2 border border-red-900/35 rounded">{explorerError}</p>
            )}
          </div>
        ) : (
          /* Authenticated Dashboard Panel Layout */
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-4">
            
            {/* Quick Actions Panel */}
            <div className="lg:col-span-5 flex flex-col gap-3">
              <h4 className="text-[10px] font-mono uppercase text-[#8E9299] flex items-center gap-1.5 font-bold">
                <UploadCloud className="w-3.5 h-3.5 text-blue-400" />
                Snapshot Report Generation
              </h4>

              {/* Status Message */}
              {exportMessage && (
                <div className={`p-2.5 border rounded text-[11px] font-mono leading-relaxed flex items-start gap-2 ${
                  exportMessage.type === 'success' 
                    ? 'bg-emerald-950/20 border-emerald-900/40 text-emerald-400' 
                    : 'bg-rose-950/20 border-rose-900/40 text-rose-400'
                }`}>
                  {exportMessage.type === 'success' ? (
                    <CheckCircle className="w-4 h-4 text-emerald-400 shrink-0 mt-0.5" />
                  ) : (
                    <AlertCircle className="w-4 h-4 text-rose-400 shrink-0 mt-0.5" />
                  )}
                  <span>{exportMessage.text}</span>
                </div>
              )}

              {/* Export Panel Options */}
              <div className="grid grid-cols-1 gap-2.5">
                {/* 1. Export Positions */}
                <div className="bg-[#1A1C1E] border border-[#2D2F31] p-3 rounded-lg flex items-center justify-between hover:border-slate-800 transition-colors">
                  <div className="flex items-start gap-2.5">
                    <div className="p-1 px-1.5 rounded mt-0.5 bg-blue-950/30 border border-blue-900/35">
                      <FileSpreadsheet className="w-3.5 h-3.5 text-blue-400" />
                    </div>
                    <div>
                      <div className="text-[11px] font-mono font-bold text-slate-100">POSITIONS SNAPSHOT (CSV)</div>
                      <div className="text-[9px] text-[#8E9299] font-mono">Snapshot {positions.length} active trade exposures.</div>
                    </div>
                  </div>

                  <button
                    onClick={handleExportPositions}
                    disabled={isExporting.positions || positions.length === 0}
                    className="p-1.5 px-3 bg-blue-900/30 text-blue-400 hover:bg-blue-600 hover:text-white rounded font-mono text-[10px] font-bold transition-all disabled:opacity-40 cursor-pointer text-center"
                    id="btn_export_positions"
                  >
                    {isExporting.positions ? 'GENERATING...' : 'EXPORT'}
                  </button>
                </div>

                {/* 2. Export Orders */}
                <div className="bg-[#1A1C1E] border border-[#2D2F31] p-3 rounded-lg flex items-center justify-between hover:border-slate-800 transition-colors">
                  <div className="flex items-start gap-2.5">
                    <div className="p-1 px-1.5 rounded mt-0.5 bg-emerald-950/30 border border-emerald-900/35">
                      <History className="w-3.5 h-3.5 text-emerald-400" />
                    </div>
                    <div>
                      <div className="text-[11px] font-mono font-bold text-slate-100">TRANSACTION REGISTRY (CSV)</div>
                      <div className="text-[9px] text-[#8E9299] font-mono">Catalog {orders.length} transaction listings.</div>
                    </div>
                  </div>

                  <button
                    onClick={handleExportOrders}
                    disabled={isExporting.orders || orders.length === 0}
                    className="p-1.5 px-3 bg-emerald-900/20 text-emerald-450 hover:bg-emerald-600 hover:text-white rounded font-mono text-[10px] font-bold transition-all disabled:opacity-40 cursor-pointer text-center"
                    id="btn_export_orders"
                  >
                    {isExporting.orders ? 'GENERATING...' : 'EXPORT'}
                  </button>
                </div>

                {/* 3. Export System Logs */}
                <div className="bg-[#1A1C1E] border border-[#2D2F31] p-3 rounded-lg flex items-center justify-between hover:border-slate-800 transition-colors">
                  <div className="flex items-start gap-2.5">
                    <div className="p-1 px-1.5 rounded mt-0.5 bg-[#2a2311]/30 border border-[#4d3d1e]/35">
                      <FileText className="w-3.5 h-3.5 text-[#ecb23e]" />
                    </div>
                    <div>
                      <div className="text-[11px] font-mono font-bold text-slate-100">SYSTEM DIAGNOSTIC AUDIT (.LOG)</div>
                      <div className="text-[9px] text-[#8E9299] font-mono">Extract {logs.length} engine tracer events.</div>
                    </div>
                  </div>

                  <button
                    onClick={handleExportLogs}
                    disabled={isExporting.logs || logs.length === 0}
                    className="p-1.5 px-3 bg-amber-950/20 text-[#ecb23e] hover:bg-amber-600 hover:text-white rounded font-mono text-[10px] font-bold transition-all disabled:opacity-40 cursor-pointer text-center"
                    id="btn_export_logs"
                  >
                    {isExporting.logs ? 'GENERATING...' : 'EXPORT'}
                  </button>
                </div>
              </div>

              {/* Integrity guidelines card */}
              <div className="bg-[#161719] border border-[#2D2F31] p-3 rounded-lg mt-1 text-[10px] font-mono text-[#8E9299] leading-relaxed">
                <div className="flex items-center gap-1 font-bold text-white mb-1.5">
                  <Lock className="w-3 h-3 text-blue-500" />
                  SECURITY & PRIVACY STATEMENT
                </div>
                <p>
                  Trade secrets and account vault credentials are encrypted server-side with AES-256-GCM and <span className="text-white">are never leaked</span> during file generations. Google Drive access is granted in a strict user-scoped manner.
                </p>
              </div>
            </div>

            {/* Google Drive Files Catalog Explorer */}
            <div className="lg:col-span-7 flex flex-col gap-3 min-h-[300px]">
              <div className="flex items-center justify-between">
                <h4 className="text-[10px] font-mono uppercase text-[#8E9299] flex items-center gap-1.5 font-bold">
                  <Cloud className="w-3.5 h-3.5 text-blue-400 animate-pulse" />
                  Terminal Files on Google Drive
                </h4>
                
                <button
                  onClick={refreshFiles}
                  disabled={isLoadingFiles}
                  className="p-1 px-1.5 bg-[#1A1C1E] border border-[#2D2F31] hover:text-white hover:bg-slate-800 disabled:opacity-50 transition-colors rounded text-[#8E9299] flex items-center gap-1 cursor-pointer text-[9px] font-mono"
                  id="btn_refresh_gdrive_explorer"
                  title="Refresh files explorer"
                >
                  <RefreshCw className={`w-2.5 h-2.5 ${isLoadingFiles ? 'animate-spin' : ''}`} />
                  <span>REFRESH LIST</span>
                </button>
              </div>

              <div className="flex-1 bg-[#1A1C1E] rounded-lg border border-[#2D2F31] overflow-hidden flex flex-col min-h-[220px]">
                {isLoadingFiles && files.length === 0 ? (
                  <div className="flex-1 flex flex-col items-center justify-center p-8 text-[#8E9299] font-mono text-[10px]">
                    <RefreshCw className="w-5 h-5 text-blue-500 animate-spin mb-2" />
                    <span>Querying Google Drive collections...</span>
                  </div>
                ) : explorerError ? (
                  <div className="flex-1 flex flex-col items-center justify-center p-8 text-center">
                    <AlertCircle className="w-6 h-6 text-red-400 mb-2" />
                    <p className="text-[11px] font-mono text-slate-350">{explorerError}</p>
                    <button
                      onClick={refreshFiles}
                      className="mt-3 p-1 px-2.5 bg-blue-900/30 text-blue-400 rounded text-[10px] font-mono hover:bg-blue-600 hover:text-white"
                    >
                      Retry Connection
                    </button>
                  </div>
                ) : files.length === 0 ? (
                  <div className="flex-1 flex flex-col items-center justify-center p-8 text-center text-[#8E9299] font-mono text-[10px]">
                    <HelpCircle className="w-6 h-6 text-[#5C5F63] mb-1.5" />
                    <span>No reports detected on Google Drive.</span>
                    <span className="text-[9px] text-[#5C5F63] mt-1">Generate a CSV snapshot on the left to populate the cloud folder.</span>
                  </div>
                ) : (
                  <div className="flex-1 overflow-x-auto">
                    <table className="w-full text-left font-mono text-[10px] border-collapse">
                      <thead>
                        <tr className="bg-[#161719] border-b border-[#2D2F31] text-[#8E9299]">
                          <th className="p-2 py-2.5 font-semibold text-[9px]">FILE NAME</th>
                          <th className="p-2 font-semibold text-[9px] text-right">SIZE</th>
                          <th className="p-2 font-semibold text-[9px] text-right">EXPORT DATE</th>
                          <th className="p-2 font-semibold text-[9px] text-center w-24">ACTIONS</th>
                        </tr>
                      </thead>
                      <tbody className="divide-y divide-[#2D2F31]">
                        {files.map(f => (
                          <tr key={f.id} className="hover:bg-[#111214] transition-colors group">
                            <td className="p-2 text-slate-200">
                              <span className="truncate block max-w-[200px]" title={f.name}>
                                {f.name}
                              </span>
                            </td>
                            <td className="p-2 text-right text-[#8E9299]">
                              {formatBytes(f.size)}
                            </td>
                            <td className="p-2 text-right text-[#8E9299]">
                              {new Date(f.createdTime).toLocaleDateString()}
                            </td>
                            <td className="p-2">
                              <div className="flex gap-1.5 justify-center">
                                {f.webViewLink && (
                                  <a
                                    href={f.webViewLink}
                                    target="_blank"
                                    rel="noreferrer"
                                    className="p-1 rounded bg-[#111214] border border-[#2D2F31] text-blue-400 hover:bg-blue-600 hover:text-white hover:border-transparent transition-all"
                                    title="Open file in Google Drive"
                                  >
                                    <ExternalLink className="w-2.5 h-2.5" />
                                  </a>
                                )}
                                <button
                                  onClick={() => handleDeleteFile(f.id, f.name)}
                                  className="p-1 rounded bg-[#111214] border border-[#2D2F31] text-red-400 hover:bg-red-600 hover:text-white hover:border-transparent transition-all cursor-pointer"
                                  title="Permanently Delete file"
                                >
                                  <Trash2 className="w-2.5 h-2.5" />
                                </button>
                              </div>
                            </td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                )}
              </div>
            </div>

          </div>
        )}
      </div>
    </div>
  );
}
